USE DATABASE STORM_EVENTS;

CREATE TABLE IF NOT EXISTS SILVER_STORM_EVENTS (
  EVENT_ID NUMBER PRIMARY KEY NOT ENFORCED,
  EPISODE_ID NUMBER,
  EVENT_YEAR NUMBER,
  EVENT_MONTH_NUMBER NUMBER,
  EVENT_MONTH VARCHAR,
  STATE VARCHAR,
  STATE_FIPS NUMBER,
  EVENT_TYPE VARCHAR,
  STORM_CATEGORY VARCHAR,
  CZ_TYPE VARCHAR,
  CZ_FIPS NUMBER,
  CZ_NAME VARCHAR,
  BEGIN_TIME TIMESTAMP_NTZ,
  END_TIME TIMESTAMP_NTZ,
  PROPERTY_DAMAGE_USD NUMBER(18,2),
  CROP_DAMAGE_USD NUMBER(18,2),
  TOTAL_DAMAGE_USD NUMBER(18,2),
  TOTAL_INJURIES NUMBER,
  TOTAL_DEATHS NUMBER,
  SEVERITY_BAND VARCHAR,
  BEGIN_LAT FLOAT,
  BEGIN_LON FLOAT,
  END_LAT FLOAT,
  END_LON FLOAT,
  SOURCE_NAME VARCHAR,
  SOURCE_FILE VARCHAR,
  INGESTION_TIME TIMESTAMP_TZ,
  RAW_RECORD_HASH NUMBER,
  QUALITY_STATUS VARCHAR
);

MERGE INTO SILVER_STORM_EVENTS AS T
USING (
  SELECT
    TRY_TO_NUMBER(EVENT_ID) AS EVENT_ID,
    TRY_TO_NUMBER(EPISODE_ID) AS EPISODE_ID,
    TRY_TO_NUMBER(YEAR) AS EVENT_YEAR,
    CASE UPPER(TRIM(MONTH_NAME))
      WHEN 'JANUARY' THEN 1 WHEN 'FEBRUARY' THEN 2 WHEN 'MARCH' THEN 3
      WHEN 'APRIL' THEN 4 WHEN 'MAY' THEN 5 WHEN 'JUNE' THEN 6
      WHEN 'JULY' THEN 7 WHEN 'AUGUST' THEN 8 WHEN 'SEPTEMBER' THEN 9
      WHEN 'OCTOBER' THEN 10 WHEN 'NOVEMBER' THEN 11 WHEN 'DECEMBER' THEN 12
    END AS EVENT_MONTH_NUMBER,
    INITCAP(TRIM(MONTH_NAME)) AS EVENT_MONTH,
    INITCAP(TRIM(STATE)) AS STATE,
    TRY_TO_NUMBER(STATE_FIPS) AS STATE_FIPS,
    INITCAP(TRIM(EVENT_TYPE)) AS EVENT_TYPE,
    UTIL.STORM_CATEGORY(EVENT_TYPE) AS STORM_CATEGORY,
    UPPER(TRIM(CZ_TYPE)) AS CZ_TYPE,
    TRY_TO_NUMBER(CZ_FIPS) AS CZ_FIPS,
    INITCAP(TRIM(CZ_NAME)) AS CZ_NAME,
    TRY_TO_TIMESTAMP_NTZ(BEGIN_DATE_TIME, 'DD-MON-YY HH24:MI:SS') AS BEGIN_TIME,
    TRY_TO_TIMESTAMP_NTZ(END_DATE_TIME, 'DD-MON-YY HH24:MI:SS') AS END_TIME,
    UTIL.PARSE_DAMAGE(DAMAGE_PROPERTY) AS PROPERTY_DAMAGE_USD,
    UTIL.PARSE_DAMAGE(DAMAGE_CROP) AS CROP_DAMAGE_USD,
    COALESCE(UTIL.PARSE_DAMAGE(DAMAGE_PROPERTY), 0) + COALESCE(UTIL.PARSE_DAMAGE(DAMAGE_CROP), 0) AS TOTAL_DAMAGE_USD,
    GREATEST(COALESCE(TRY_TO_NUMBER(INJURIES_DIRECT), 0) + COALESCE(TRY_TO_NUMBER(INJURIES_INDIRECT), 0), 0) AS TOTAL_INJURIES,
    GREATEST(COALESCE(TRY_TO_NUMBER(DEATHS_DIRECT), 0) + COALESCE(TRY_TO_NUMBER(DEATHS_INDIRECT), 0), 0) AS TOTAL_DEATHS,
    UTIL.SEVERITY_BAND(
      COALESCE(UTIL.PARSE_DAMAGE(DAMAGE_PROPERTY), 0) + COALESCE(UTIL.PARSE_DAMAGE(DAMAGE_CROP), 0),
      COALESCE(TRY_TO_NUMBER(INJURIES_DIRECT), 0) + COALESCE(TRY_TO_NUMBER(INJURIES_INDIRECT), 0),
      COALESCE(TRY_TO_NUMBER(DEATHS_DIRECT), 0) + COALESCE(TRY_TO_NUMBER(DEATHS_INDIRECT), 0)
    ) AS SEVERITY_BAND,
    TRY_TO_DOUBLE(BEGIN_LAT) AS BEGIN_LAT,
    TRY_TO_DOUBLE(BEGIN_LON) AS BEGIN_LON,
    TRY_TO_DOUBLE(END_LAT) AS END_LAT,
    TRY_TO_DOUBLE(END_LON) AS END_LON,
    SOURCE AS SOURCE_NAME,
    SOURCE_FILE,
    INGESTION_TIME,
    HASH(EVENT_ID, EPISODE_ID, YEAR, STATE, EVENT_TYPE, BEGIN_DATE_TIME, END_DATE_TIME,
         DAMAGE_PROPERTY, DAMAGE_CROP, INJURIES_DIRECT, INJURIES_INDIRECT,
         DEATHS_DIRECT, DEATHS_INDIRECT) AS RAW_RECORD_HASH,
    CASE
      WHEN TRY_TO_NUMBER(EVENT_ID) IS NULL OR STATE IS NULL OR EVENT_TYPE IS NULL THEN 'Review'
      WHEN UTIL.PARSE_DAMAGE(DAMAGE_PROPERTY) IS NULL OR UTIL.PARSE_DAMAGE(DAMAGE_CROP) IS NULL THEN 'Review'
      WHEN TRY_TO_TIMESTAMP_NTZ(BEGIN_DATE_TIME, 'DD-MON-YY HH24:MI:SS') IS NULL THEN 'Review'
      ELSE 'Accepted'
    END AS QUALITY_STATUS
  FROM BRONZE_STORM_EVENTS
  WHERE TRY_TO_NUMBER(YEAR) BETWEEN 2022 AND 2024
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRY_TO_NUMBER(EVENT_ID)
    ORDER BY INGESTION_TIME DESC
  ) = 1
) AS S
ON T.EVENT_ID = S.EVENT_ID
WHEN NOT MATCHED THEN INSERT (
  EVENT_ID, EPISODE_ID, EVENT_YEAR, EVENT_MONTH_NUMBER, EVENT_MONTH, STATE,
  STATE_FIPS, EVENT_TYPE, STORM_CATEGORY, CZ_TYPE, CZ_FIPS, CZ_NAME,
  BEGIN_TIME, END_TIME, PROPERTY_DAMAGE_USD, CROP_DAMAGE_USD, TOTAL_DAMAGE_USD,
  TOTAL_INJURIES, TOTAL_DEATHS, SEVERITY_BAND, BEGIN_LAT, BEGIN_LON, END_LAT,
  END_LON, SOURCE_NAME, SOURCE_FILE, INGESTION_TIME,
  RAW_RECORD_HASH, QUALITY_STATUS
) VALUES (
  S.EVENT_ID, S.EPISODE_ID, S.EVENT_YEAR, S.EVENT_MONTH_NUMBER, S.EVENT_MONTH, S.STATE,
  S.STATE_FIPS, S.EVENT_TYPE, S.STORM_CATEGORY, S.CZ_TYPE, S.CZ_FIPS, S.CZ_NAME,
  S.BEGIN_TIME, S.END_TIME, S.PROPERTY_DAMAGE_USD, S.CROP_DAMAGE_USD, S.TOTAL_DAMAGE_USD,
  S.TOTAL_INJURIES, S.TOTAL_DEATHS, S.SEVERITY_BAND, S.BEGIN_LAT, S.BEGIN_LON,
  S.END_LAT, S.END_LON, S.SOURCE_NAME, S.SOURCE_FILE,
  S.INGESTION_TIME, S.RAW_RECORD_HASH, S.QUALITY_STATUS
);

SELECT EVENT_YEAR, COUNT(*) AS CLEAN_ROWS,
       COUNT_IF(QUALITY_STATUS = 'Review') AS REVIEW_ROWS
FROM SILVER_STORM_EVENTS
GROUP BY EVENT_YEAR
ORDER BY EVENT_YEAR;

