USE DATABASE storm_events;

-- creating pipe
CREATE OR REPLACE PIPE storm_events_pipe
    AUTO_INGEST = FALSE
AS
COPY INTO bronze_storm_events
(BEGIN_YEARMONTH, BEGIN_DAY, BEGIN_TIME, END_YEARMONTH, END_DAY, END_TIME, EPISODE_ID, EVENT_ID, STATE, STATE_FIPS, YEAR, MONTH_NAME, EVENT_TYPE, CZ_TYPE, CZ_FIPS, CZ_NAME, WFO, BEGIN_DATE_TIME, CZ_TIMEZONE, END_DATE_TIME, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGE_PROPERTY, DAMAGE_CROP, SOURCE, MAGNITUDE, MAGNITUDE_TYPE, FLOOD_CAUSE, CATEGORY, TOR_F_SCALE, TOR_LENGTH, TOR_WIDTH, TOR_OTHER_WFO, TOR_OTHER_CZ_STATE, TOR_OTHER_CZ_FIPS, TOR_OTHER_CZ_NAME, BEGIN_RANGE, BEGIN_AZIMUTH, BEGIN_LOCATION, END_RANGE, END_AZIMUTH, END_LOCATION, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON, EPISODE_NARRATIVE, EVENT_NARRATIVE, DATA_SOURCE, SOURCE_FILE, INGESTION_TIME, SOURCE_URL)
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, METADATA$FILENAME, CURRENT_TIMESTAMP(), 
'https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/' || METADATA$FILENAME
FROM @event_raw_stage)
FILE_FORMAT = event_raw_format
ON_ERROR = 'CONTINUE';

-- create stream to capture only the new rows
CREATE OR REPLACE STREAM bronze_storm_events_stream
ON TABLE bronze_storm_events;

-- Bronze table row count before new file
SELECT COUNT(*)
FROM bronze_storm_events;

-- stream row count before the loading
SELECT COUNT(*) FROM bronze_storm_events_stream;

-- trigger pipe refresh
ALTER PIPE storm_events_pipe REFRESH;

-- new count for bronze table after file
SELECT COUNT(*)
FROM bronze_storm_events;

-- sample of stream
SELECT * FROM bronze_storm_events_stream
LIMIT 10;

-- stream row count after loading
SELECT COUNT(*) FROM bronze_storm_events_stream;

MERGE INTO SILVER_STORM_EVENTS AS T
USING (
  SELECT
    TRY_TO_NUMBER(EVENT_ID) AS EVENT_ID,
    TRY_TO_NUMBER(EPISODE_ID) AS EPISODE_ID,
    TRY_TO_NUMBER(YEAR) AS EVENT_YEAR,
    CASE UPPER(TRIM(MONTH_NAME))
      WHEN 'JANUARY' THEN 1 WHEN 'FEBRUARY' THEN 2 WHEN 'MARCH' THEN 3
      WHEN 'APRIL' THEN 4 WHEN 'MAY' THEN 5 WHEN 'JUNE' THEN 6
      WHEN 'JULY' THEN 7 WHEN 'AUGUST' THEN 8 WHEN 'SEPTEMBER' THEN 9
      WHEN 'OCTOBER' THEN 10 WHEN 'NOVEMBER' THEN 11 WHEN 'DECEMBER' THEN 12
    END AS EVENT_MONTH_NUMBER,
    INITCAP(TRIM(MONTH_NAME)) AS EVENT_MONTH,
    INITCAP(TRIM(STATE)) AS STATE,
    TRY_TO_NUMBER(STATE_FIPS) AS STATE_FIPS,
    INITCAP(TRIM(EVENT_TYPE)) AS EVENT_TYPE,
    UTIL.STORM_CATEGORY(EVENT_TYPE) AS STORM_CATEGORY,
    UPPER(TRIM(CZ_TYPE)) AS CZ_TYPE,
    TRY_TO_NUMBER(CZ_FIPS) AS CZ_FIPS,
    INITCAP(TRIM(CZ_NAME)) AS CZ_NAME,
    TRY_TO_TIMESTAMP_NTZ(BEGIN_DATE_TIME, 'DD-MON-YY HH24:MI:SS') AS BEGIN_TIME,
    TRY_TO_TIMESTAMP_NTZ(END_DATE_TIME, 'DD-MON-YY HH24:MI:SS') AS END_TIME,
    UTIL.PARSE_DAMAGE(DAMAGE_PROPERTY) AS PROPERTY_DAMAGE_USD,
    UTIL.PARSE_DAMAGE(DAMAGE_CROP) AS CROP_DAMAGE_USD,
    COALESCE(UTIL.PARSE_DAMAGE(DAMAGE_PROPERTY), 0) + COALESCE(UTIL.PARSE_DAMAGE(DAMAGE_CROP), 0) AS TOTAL_DAMAGE_USD,
    GREATEST(COALESCE(TRY_TO_NUMBER(INJURIES_DIRECT), 0) + COALESCE(TRY_TO_NUMBER(INJURIES_INDIRECT), 0), 0) AS TOTAL_INJURIES,
    GREATEST(COALESCE(TRY_TO_NUMBER(DEATHS_DIRECT), 0) + COALESCE(TRY_TO_NUMBER(DEATHS_INDIRECT), 0), 0) AS TOTAL_DEATHS,
    UTIL.SEVERITY_BAND(
      COALESCE(UTIL.PARSE_DAMAGE(DAMAGE_PROPERTY), 0) + COALESCE(UTIL.PARSE_DAMAGE(DAMAGE_CROP), 0),
      COALESCE(TRY_TO_NUMBER(INJURIES_DIRECT), 0) + COALESCE(TRY_TO_NUMBER(INJURIES_INDIRECT), 0),
      COALESCE(TRY_TO_NUMBER(DEATHS_DIRECT), 0) + COALESCE(TRY_TO_NUMBER(DEATHS_INDIRECT), 0)
    ) AS SEVERITY_BAND,
    TRY_TO_DOUBLE(BEGIN_LAT) AS BEGIN_LAT,
    TRY_TO_DOUBLE(BEGIN_LON) AS BEGIN_LON,
    TRY_TO_DOUBLE(END_LAT) AS END_LAT,
    TRY_TO_DOUBLE(END_LON) AS END_LON,
    SOURCE AS SOURCE_NAME,
    SOURCE_FILE,
    INGESTION_TIME,
    HASH(EVENT_ID, EPISODE_ID, YEAR, STATE, EVENT_TYPE, BEGIN_DATE_TIME, END_DATE_TIME,
         DAMAGE_PROPERTY, DAMAGE_CROP, INJURIES_DIRECT, INJURIES_INDIRECT,
         DEATHS_DIRECT, DEATHS_INDIRECT) AS RAW_RECORD_HASH,
    CASE
      WHEN TRY_TO_NUMBER(EVENT_ID) IS NULL OR STATE IS NULL OR EVENT_TYPE IS NULL THEN 'Review'
      WHEN UTIL.PARSE_DAMAGE(DAMAGE_PROPERTY) IS NULL OR UTIL.PARSE_DAMAGE(DAMAGE_CROP) IS NULL THEN 'Review'
      WHEN TRY_TO_TIMESTAMP_NTZ(BEGIN_DATE_TIME, 'DD-MON-YY HH24:MI:SS') IS NULL THEN 'Review'
      ELSE 'Accepted'
    END AS QUALITY_STATUS
  FROM BRONZE_STORM_EVENTS
  WHERE YEAR = 2025
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRY_TO_NUMBER(EVENT_ID)
    ORDER BY INGESTION_TIME DESC
  ) = 1
) AS S
ON T.EVENT_ID = S.EVENT_ID
WHEN NOT MATCHED THEN INSERT (
  EVENT_ID, EPISODE_ID, EVENT_YEAR, EVENT_MONTH_NUMBER, EVENT_MONTH, STATE,
  STATE_FIPS, EVENT_TYPE, STORM_CATEGORY, CZ_TYPE, CZ_FIPS, CZ_NAME,
  BEGIN_TIME, END_TIME, PROPERTY_DAMAGE_USD, CROP_DAMAGE_USD, TOTAL_DAMAGE_USD,
  TOTAL_INJURIES, TOTAL_DEATHS, SEVERITY_BAND, BEGIN_LAT, BEGIN_LON, END_LAT,
  END_LON, SOURCE_NAME, SOURCE_FILE, INGESTION_TIME,
  RAW_RECORD_HASH, QUALITY_STATUS
) VALUES (
  S.EVENT_ID, S.EPISODE_ID, S.EVENT_YEAR, S.EVENT_MONTH_NUMBER, S.EVENT_MONTH, S.STATE,
  S.STATE_FIPS, S.EVENT_TYPE, S.STORM_CATEGORY, S.CZ_TYPE, S.CZ_FIPS, S.CZ_NAME,
  S.BEGIN_TIME, S.END_TIME, S.PROPERTY_DAMAGE_USD, S.CROP_DAMAGE_USD, S.TOTAL_DAMAGE_USD,
  S.TOTAL_INJURIES, S.TOTAL_DEATHS, S.SEVERITY_BAND, S.BEGIN_LAT, S.BEGIN_LON,
  S.END_LAT, S.END_LON, S.SOURCE_NAME, S.SOURCE_FILE,
  S.INGESTION_TIME, S.RAW_RECORD_HASH, S.QUALITY_STATUS
);