USE DATABASE STORM_EVENTS;
CREATE SCHEMA IF NOT EXISTS REPORTING;

CREATE OR REPLACE VIEW VW_STORM_EVENTS AS
SELECT
  EVENT_ID, EPISODE_ID, EVENT_YEAR, EVENT_MONTH_NUMBER, EVENT_MONTH,
  STATE, STATE_FIPS, EVENT_TYPE, STORM_CATEGORY, CZ_TYPE, CZ_FIPS, CZ_NAME,
  BEGIN_TIME, END_TIME, PROPERTY_DAMAGE_USD, CROP_DAMAGE_USD, TOTAL_DAMAGE_USD,
  TOTAL_INJURIES, TOTAL_DEATHS, SEVERITY_BAND,
  BEGIN_LAT, BEGIN_LON, END_LAT, END_LON,
  SOURCE_FILE, INGESTION_TIME
FROM SILVER_STORM_EVENTS
WHERE QUALITY_STATUS = 'Accepted';

CREATE OR REPLACE VIEW VW_YEARLY_ACTIVITY AS
SELECT
  EVENT_YEAR,
  COUNT(*) AS EVENT_COUNT,
  SUM(PROPERTY_DAMAGE_USD) AS PROPERTY_DAMAGE_USD,
  SUM(CROP_DAMAGE_USD) AS CROP_DAMAGE_USD,
  SUM(TOTAL_DAMAGE_USD) AS TOTAL_DAMAGE_USD,
  SUM(TOTAL_INJURIES) AS TOTAL_INJURIES,
  SUM(TOTAL_DEATHS) AS TOTAL_DEATHS,
  LAG(COUNT(*)) OVER (ORDER BY EVENT_YEAR) AS PRIOR_YEAR_EVENTS,
  COUNT(*) - LAG(COUNT(*)) OVER (ORDER BY EVENT_YEAR) AS YEARLY_EVENT_CHANGE,
  DIV0(COUNT(*) - LAG(COUNT(*)) OVER (ORDER BY EVENT_YEAR),
       LAG(COUNT(*)) OVER (ORDER BY EVENT_YEAR)) AS YEARLY_EVENT_CHANGE_PCT
FROM VW_STORM_EVENTS
GROUP BY EVENT_YEAR;

CREATE OR REPLACE VIEW VW_EVENT_TYPE_SUMMARY AS
SELECT EVENT_TYPE, STORM_CATEGORY,
       COUNT(*) AS EVENT_COUNT,
       COUNT(DISTINCT STATE) AS STATES_AFFECTED,
       SUM(TOTAL_DAMAGE_USD) AS TOTAL_DAMAGE_USD,
       SUM(TOTAL_INJURIES) AS TOTAL_INJURIES,
       SUM(TOTAL_DEATHS) AS TOTAL_DEATHS
FROM VW_STORM_EVENTS
GROUP BY EVENT_TYPE, STORM_CATEGORY;

CREATE OR REPLACE VIEW VW_MONTHLY_ACTIVITY AS
SELECT EVENT_MONTH_NUMBER, EVENT_MONTH,
       COUNT(*) AS EVENT_COUNT,
       SUM(TOTAL_DAMAGE_USD) AS TOTAL_DAMAGE_USD
FROM VW_STORM_EVENTS
GROUP BY EVENT_MONTH_NUMBER, EVENT_MONTH;

CREATE OR REPLACE VIEW VW_STATE_RISK AS
WITH STATE_BASE AS (
  SELECT STATE,
         COUNT(*) AS EVENT_COUNT,
         COUNT(DISTINCT EVENT_YEAR) AS YEARS_AFFECTED,
         SUM(PROPERTY_DAMAGE_USD) AS PROPERTY_DAMAGE_USD,
         SUM(CROP_DAMAGE_USD) AS CROP_DAMAGE_USD,
         SUM(TOTAL_DAMAGE_USD) AS TOTAL_DAMAGE_USD,
         SUM(TOTAL_INJURIES) AS TOTAL_INJURIES,
         SUM(TOTAL_DEATHS) AS TOTAL_DEATHS,
         SUM(TOTAL_INJURIES + TOTAL_DEATHS) AS CASUALTIES
  FROM VW_STORM_EVENTS
  GROUP BY STATE
), SCORED AS (
  SELECT *,
         PERCENT_RANK() OVER (ORDER BY EVENT_COUNT) AS FREQUENCY_PERCENTILE,
         PERCENT_RANK() OVER (ORDER BY TOTAL_DAMAGE_USD) AS DAMAGE_PERCENTILE,
         PERCENT_RANK() OVER (ORDER BY CASUALTIES) AS CASUALTY_PERCENTILE
  FROM STATE_BASE
)
SELECT *, ROUND(100 * (
    0.35 * FREQUENCY_PERCENTILE
  + 0.45 * DAMAGE_PERCENTILE
  + 0.20 * CASUALTY_PERCENTILE
), 2) AS RISK_SCORE
FROM SCORED;

CREATE OR REPLACE VIEW VW_STATE_EVENT_MATRIX AS
SELECT STATE, EVENT_TYPE,
       COUNT(*) AS EVENT_COUNT,
       SUM(TOTAL_DAMAGE_USD) AS TOTAL_DAMAGE_USD
FROM VW_STORM_EVENTS
GROUP BY STATE, EVENT_TYPE;

SELECT * FROM VW_YEARLY_ACTIVITY ORDER BY EVENT_YEAR;
SELECT * FROM VW_STATE_RISK ORDER BY RISK_SCORE DESC LIMIT 10;

