USE DATABASE STORM_EVENTS;

CREATE SCHEMA IF NOT EXISTS storm_events.util;

CREATE OR REPLACE FUNCTION UTIL.PARSE_DAMAGE(RAW_VALUE VARCHAR)
RETURNS NUMBER(18,2)
LANGUAGE SQL
AS
$$
  CASE
    WHEN RAW_VALUE IS NULL OR TRIM(RAW_VALUE) = '' THEN 0
    WHEN UPPER(TRIM(RAW_VALUE)) RLIKE '^[0-9]+([.][0-9]+)?[KMB]?$' THEN
      TRY_TO_DECIMAL(REGEXP_SUBSTR(UPPER(TRIM(RAW_VALUE)), '^[0-9]+([.][0-9]+)?'), 18, 2)
      * CASE RIGHT(UPPER(TRIM(RAW_VALUE)), 1)
          WHEN 'K' THEN 1000
          WHEN 'M' THEN 1000000
          WHEN 'B' THEN 1000000000
          ELSE 1
        END
    ELSE NULL
  END
$$;

CREATE OR REPLACE FUNCTION UTIL.STORM_CATEGORY(EVENT_NAME VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
  CASE
    WHEN UPPER(EVENT_NAME) LIKE '%TORNADO%' OR UPPER(EVENT_NAME) LIKE '%FUNNEL CLOUD%' OR UPPER(EVENT_NAME) LIKE '%WATERSPOUT%' THEN 'Tornado and Rotation'
    WHEN UPPER(EVENT_NAME) LIKE '%HAIL%' THEN 'Hail'
    WHEN UPPER(EVENT_NAME) LIKE '%FLOOD%' OR UPPER(EVENT_NAME) LIKE '%HEAVY RAIN%' OR UPPER(EVENT_NAME) LIKE '%DEBRIS FLOW%' THEN 'Flood and Heavy Rain'
    WHEN UPPER(EVENT_NAME) LIKE '%THUNDERSTORM%' OR UPPER(EVENT_NAME) LIKE '%LIGHTNING%' THEN 'Thunderstorm'
    WHEN UPPER(EVENT_NAME) LIKE '%WIND%' THEN 'Wind'
    WHEN UPPER(EVENT_NAME) LIKE '%WINTER%' OR UPPER(EVENT_NAME) LIKE '%SNOW%' OR UPPER(EVENT_NAME) LIKE '%ICE%' OR UPPER(EVENT_NAME) LIKE '%BLIZZARD%' OR UPPER(EVENT_NAME) LIKE '%COLD%' OR UPPER(EVENT_NAME) LIKE '%FROST%' OR UPPER(EVENT_NAME) LIKE '%AVALANCHE%' THEN 'Winter Weather'
    WHEN UPPER(EVENT_NAME) LIKE '%HURRICANE%' OR UPPER(EVENT_NAME) LIKE '%TROPICAL%' OR UPPER(EVENT_NAME) LIKE '%STORM SURGE%' THEN 'Tropical'
    WHEN UPPER(EVENT_NAME) LIKE '%HEAT%' OR UPPER(EVENT_NAME) LIKE '%DROUGHT%' OR UPPER(EVENT_NAME) LIKE '%WILDFIRE%' OR UPPER(EVENT_NAME) LIKE '%FIRE WEATHER%' THEN 'Heat, Drought and Fire'
    WHEN UPPER(EVENT_NAME) LIKE '%COASTAL%' OR UPPER(EVENT_NAME) LIKE '%HIGH SURF%' OR UPPER(EVENT_NAME) LIKE '%RIP CURRENT%' OR UPPER(EVENT_NAME) LIKE '%TSUNAMI%' OR UPPER(EVENT_NAME) LIKE '%SLEET%' THEN 'Coastal and Other'
    ELSE 'Other'
  END
$$;

CREATE OR REPLACE FUNCTION UTIL.SEVERITY_BAND(
  TOTAL_DAMAGE NUMBER, TOTAL_INJURIES NUMBER, TOTAL_DEATHS NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
  CASE
    WHEN COALESCE(TOTAL_DEATHS, 0) > 0 OR COALESCE(TOTAL_DAMAGE, 0) >= 10000000 THEN 'Critical'
    WHEN COALESCE(TOTAL_INJURIES, 0) >= 10 OR COALESCE(TOTAL_DAMAGE, 0) >= 1000000 THEN 'High'
    WHEN COALESCE(TOTAL_INJURIES, 0) > 0 OR COALESCE(TOTAL_DAMAGE, 0) >= 100000 THEN 'Moderate'
    ELSE 'Low'
  END
$$;

SELECT UTIL.PARSE_DAMAGE('2.5M') AS EXPECTED_2500000,
       UTIL.STORM_CATEGORY('Flash Flood') AS EXPECTED_FLOOD,
       UTIL.SEVERITY_BAND(12000000, 0, 0) AS EXPECTED_CRITICAL;
