CREATE DATABASE IF NOT EXISTS storm_events;

-- create table
CREATE TABLE IF NOT EXISTS bronze_storm_events (
BEGIN_YEARMONTH INT,
BEGIN_DAY INT,
BEGIN_TIME INT,
END_YEARMONTH INT,
END_DAY INT,
END_TIME INT,
EPISODE_ID INT,
EVENT_ID INT,
STATE VARCHAR,
STATE_FIPS INT,
YEAR INT,
MONTH_NAME VARCHAR,
EVENT_TYPE VARCHAR,
CZ_TYPE VARCHAR,
CZ_FIPS INT,
CZ_NAME VARCHAR,
WFO CHAR(3),
BEGIN_DATE_TIME VARCHAR,
CZ_TIMEZONE VARCHAR,
END_DATE_TIME VARCHAR,
INJURIES_DIRECT INT,
INJURIES_INDIRECT INT,
DEATHS_DIRECT INT,
DEATHS_INDIRECT INT,
DAMAGE_PROPERTY VARCHAR,
DAMAGE_CROP VARCHAR,
SOURCE VARCHAR,
MAGNITUDE DOUBLE,
MAGNITUDE_TYPE VARCHAR,
FLOOD_CAUSE VARCHAR,
CATEGORY INT,
TOR_F_SCALE VARCHAR,
TOR_LENGTH DOUBLE,
TOR_WIDTH DOUBLE,
TOR_OTHER_WFO VARCHAR,
TOR_OTHER_CZ_STATE VARCHAR,
TOR_OTHER_CZ_FIPS INT,
TOR_OTHER_CZ_NAME VARCHAR,
BEGIN_RANGE DOUBLE,
BEGIN_AZIMUTH VARCHAR,
BEGIN_LOCATION VARCHAR,
END_RANGE DOUBLE,
END_AZIMUTH VARCHAR,
END_LOCATION VARCHAR,
BEGIN_LAT DOUBLE,
BEGIN_LON DOUBLE,
END_LAT DOUBLE,
END_LON DOUBLE,
EPISODE_NARRATIVE VARCHAR,
EVENT_NARRATIVE VARCHAR,
DATA_SOURCE VARCHAR,
SOURCE_FILE VARCHAR,
INGESTION_TIME TIMESTAMP,
SOURCE_URL VARCHAR
);

-- create format
CREATE FILE FORMAT IF NOT EXISTS event_raw_format
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE;

-- create stage
CREATE STAGE IF NOT EXISTS event_raw_stage;

-- Show current files
LIST @event_raw_stage;

-- Load into bronze table
COPY INTO bronze_storm_events
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, METADATA$FILENAME, CURRENT_TIMESTAMP(),
    'https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/' || METADATA$FILENAME
FROM @event_raw_stage) 
FILE_FORMAT = event_raw_format;

-- Sample rows
SELECT * FROM bronze_storm_events
LIMIT 10;

-- Count per file
SELECT YEAR, SOURCE_FILE, COUNT(*) FROM bronze_storm_events
GROUP BY YEAR, SOURCE_FILE
ORDER BY YEAR;

-- Total count
SELECT COUNT(*) FROM bronze_storm_events;